apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pc-sc
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - mfsymlinks
  - actimeo=30
  - nosharesock
parameters:
  skuName: Standard_LRS
